### ISSUE TITLE
Create Blogpost, View Blogpost and List all blogposts

### ISSUE THREAD

**Issue by TheMarv** [TheMarv/capstone-project#1]
### Value definition
As a user I want to create a new blogpost in a form, view the blogpost I created and have a list of all blogposts.

![image](https://user-images.githubusercontent.com/15978350/170045890-c375f234-07cc-4064-ae90-ee13e8845c34.png)

### Acceptance criteria 

- [x] title input length: 5 < n < 100
- [x] content input length: 10 < n < 5000
- [x] creation date of post is displayed
- [x] save button saves post 
- [x] the new blog posts should be shown on the main page
- [x] the new blog posts should have an own page on blog/[id]
- [x] submit should clear the form

### Tasks

- [x] Create a new branch
- [x] Create a form with two inputs (1 text, 1 textarea) and a submit button
- [x] Create a page for a singular blogpost
- [x] Create a page to list all blogposts
- [x] Add a submit function that saves the posts in a global state

### Complexity

low

**Comment by marcbendixen** [comment]
Hey,
looks really good to me 👍 i have nothing to add here.
As already mentioned this morning: be careful with big PRs 😉 because this is too much for one PR in my opinion.
