### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by TheMarv** [TheMarv/capstone-project#13]
### Value definition

As a User,
I want to have a header with a logo and menu icon,
so that I can access the menu at any time.

### Acceptance Criteria 

- [x] Header is always at the top of the screen
- [x] Header is always on top except if the menu is open
- [x] Burger icon opens the menu
- [x] Click on logo redirects to /

### Tasks

- [x] Create header component
- [x] Link logo to /
- [x] Add burger icon that opens the menu

### Complexity

low

**Comment by alexclaes** [comment]
Hi Marvin, good and brief user story!
