### ISSUE TITLE
Visual Feedback on user input

### ISSUE THREAD

**Issue by TheMarv** [TheMarv/capstone-project#14]
### Value definition

As a User,
I want to have a feedback on forms,
so that I know that my input was saved.

### AC

- [x] Implement toasts globally
- [x] Toasts should appear on every user input with according colors and icons
- [x] Toasts should automatically close after 4.5 seconds
- [x] Toasts should be dismissable
- [x] Toasts should be centred on the bottom of the screen

### Tasks

- [x] Create snackbar component
- [x] Add a global store for toasts 
- [x] Implement toasts on snackbar component
- [x] Make toasts disappear after 4.5 seconds
- [x] Make toasts dismissable
- [x] Exclude toasts from being saved in localStorage
- [x] Add toasts to every user input form:
   - [x] Create Blogpost
   - [x] Create Category

### Complexity

low

**Comment by oy-gen** [comment]
lgtm
