### ISSUE TITLE
WYSIWYG Editor for blogposts

### ISSUE THREAD

**Issue by TheMarv** [TheMarv/capstone-project#15]
### Value definition

As a User,
I want to have a better editor,
so that I can style my blogposts better.

### AC

- [x] WYSIWYG editor instead of textarea on blogposts
- [x] Text keeps the formation from the editor

### Tasks

- [x] Install WYSIWYG package
- [x] Replace textarea with editor on create blogpost page
- [x] Implement the html from the editor on the blogposts

### Complexity

low

**Comment by F-Kirchhoff** [comment]
Hey Marvin, you could specify what 'better editor' means, besides that your userstory is fine.
