### ISSUE TITLE
Manage categories

### ISSUE THREAD

**Issue by TheMarv** [TheMarv/capstone-project#21]
### Value definition

As an admin,
I want to manage my categories,
so that I can change them at any time.

### AC

- [ ] All categories are listed in a table
- [ ] Categories can be deleted via a button in the table
- [ ] Categories can be edit via a button in the table

### Tasks

- [ ] Create a page for listing the categories
- [ ] Fit all categories into one table
- [ ] Add a delete button
   - [ ] Add a modal, that verifies if the admin wants to delete the category
   - [ ] Remove category from state
- [ ] Add an edit button
   - [ ] Edit button redirects to edit page
   - [ ] Replace old category with the updated category in state

### Complexity

medium

**Comment by Chaosfuchs** [comment]
LGTM :)
