### ISSUE TITLE
Manage Blogposts

### ISSUE THREAD

**Issue by TheMarv** [TheMarv/capstone-project#24]
### Value definition

As an admin,
I want to manage my blogposts,
so that I can change them at any time.

### AC

- [ ] All blogposts are listed in a table
- [ ] Blogposts can be deleted via a button in the table
- [ ] Blogposts can be edit via a button in the table

### Tasks

- [ ] Create a page for listing the blogposts
- [ ] Fit all blogposts into one table
- [ ] Add a delete button
   - [ ] Add a modal, that verifies if the admin wants to delete the blogpost
   - [ ] Remove blogpost from state
- [ ] Add an edit button
   - [ ] #25

**Comment by marcbendixen** [comment]
Hey 👋 looks good to me and the idea of creating a seperate issue for the edit function is perfectly fine 👍
