### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by TheMarv** [TheMarv/capstone-project#4]
### Value Definition

As a user,
I want to navigate inside the app,
so that I can easily switch between the pages/forms.

![Untitled-2022-05-30-1409-3](https://user-images.githubusercontent.com/15978350/170994011-d4681a1a-1a4b-4dcb-b11a-bed1a18e98fb.png)

### Acceptance Criteria

- [x] Menu should be visually separated between `main` and `admin` links
- [x] Main:
   - [x] Home
   - [x] Blogposts
   - [x] every single category
- [x] Admin:
   - [x] Create Blogpost
   - [x] Create Category

### Tasks

- [x] Add menu component
- [x] Add links
- [x] List categories
- [x] Add open/close function

### Complexity

low

**Comment by marcbendixen** [comment]
Hey 👋 

good job, I have two comments on that:

- I would prefer a different value definition like the following, because my need as a user is not a menu itself, but changing pages:
"As a user
I want to be able to navigate inside the app
so that I can easily switch between pages and forms."

- You forgot the list of tasks.

**Comment by Chaosfuchs** [comment]
lgtm :) I think you will create a hamburger menu? Thats nice 🚀
