### ISSUE TITLE
Persistent data

### ISSUE THREAD

**Issue by TheMarv** [TheMarv/capstone-project#5]
### Value Definition

As a user,
I want my data to be saved,
so that the data is still there when I reopen the page.

### Acceptance Criteria 

- [x] All user related data (Blogposts, Categories and data not yet covered) should be saved in the localStorage
- [x] When opening the page, all data should be loaded from localStorage if there is data available

### Tasks
 
- [x] Create a new branch
- [x] Implement saving and loading from localStorage

### Complexity

low
