### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by TheMarv** [TheMarv/capstone-project#6]
### Value definition

As a User
I want to add new categories
so that I can organise my blogposts.

### Acceptance Criteria

- [x] Category length: 5 < n < 100
- [x] Slug length: 5 < n < 100
- [x] Slug only consists out of lowercase characters, numbers and a dash
- [x] The form is on a new page
- [x] Slug is dynamically generated from name, but can be altered by user
- [x] Saving adds category to the global state

### Tasks

- [x] Create a new branch
- [x] Create a form with two text inputs and a submit button
- [x] Save category in global state

### Complexity

low

**Comment by Luxa23** [comment]
hi @TheMarv,

this looks good so far, but I believe that tasks and AC are a bit mixed up. 
The ACs "Slug is dynamically generated..." and "Saving adds category.." are actual tasks for the developer since the user is not really interested where data are saved. Instead you could write as a AC that the user can change the slug's name. And also that the user can create a new category.

Maybe you could add some more details to the tasks, for example "create a new page" in case it doesn't exist yet or "make sure that length restrictions are respected". 

Just remember that AC are written from the user's perspective and the tasks are for the dev team :)
Let me know if you have any questions.
