### ISSUE TITLE
Categorise Blogposts

### ISSUE THREAD

**Issue by TheMarv** [TheMarv/capstone-project#7]
### Value definition

As a User,
I want to categorise my blogposts,
so that I can organise my blogposts.

### AC

- [x] Create blogpost has a select element named categories
- [x] Select element has options for each category & uncategorised
- [x] Save the blogpost with the category
- [x] Display category in the blogpost

### Tasks

- [x] Add select element to create blogpost page
- [x] Add option for each category 
- [x] Add default option uncategorised
- [x] Add the category to the new blogpost object
- [x] Display the category in the blogpost

### Complexity

low

**Comment by F-Kirchhoff** [comment]
LGTM 🚀
