### ISSUE TITLE
Category pages

### ISSUE THREAD

**Issue by TheMarv** [TheMarv/capstone-project#8]
### Value definition

As a user,
I want to view all blogposts of a category,
so that it is easier to pick the right blogpost.

### AC

- [x] Each category has it's own page
- [x] The page of the category displays only posts of the category

### Tasks

- [x] Create a page with [categorySlug] identifier
- [x] Filter posts by categorySlug
- [x] Display filtered posts

### Complexity

low

**Comment by Chaosfuchs** [comment]
LGTM :)
